# Generated by Django 2.2.5 on 2019-12-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191215_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Select language'), ('english', 'English'), ('korean', 'Korean')], default='english', max_length=2, null=True, verbose_name='language'),
        ),
    ]
