# Generated by Django 2.2.5 on 2019-10-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20191027_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='baths',
            new_name='bathrooms',
        ),
    ]
