# Generated by Django 2.2.5 on 2019-11-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20191028_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='instance_book',
            new_name='instant_book',
        ),
    ]
