# Generated by Django 2.2.5 on 2019-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20191107_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='subdir',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='room_photos/<django.db.models.fields.IntegerField>'),
        ),
    ]
