# Generated by Django 2.2.5 on 2019-12-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20191215_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='subdir',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='room_photos'),
        ),
    ]
