# Generated by Django 2.2.5 on 2019-12-15 21:03

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20191215_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=rooms.models.get_upload_to),
        ),
    ]
