# Generated by Django 2.2.5 on 2019-12-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
    ]
