# Generated by Django 2.2.5 on 2019-12-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20191127_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['check_in', 'check_out']},
        ),
    ]
